version: 2
jobs:
  build-linux-default:
    machine: true
    steps:
      - checkout
      - run:
          name: Make scripts executable 
          command: sudo chmod -R +x ./.circleci/*.sh
      - run:
          name: Install
          command: ./.circleci/install_platform_io.sh
      - run:
          name: Build
          command: ./.circleci/script_platform_io.sh
  build-linux-gcc7:
    machine: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get remove cmake cmake-data
            sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test 
            sudo apt-add-repository -y ppa:george-edison55/cmake-3.x
            sudo apt-get update
            sudo apt-get -y install g++-7 gcc-7 lcov cmake
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
            sudo update-alternatives --config gcc
      - run:
          name: Make scripts executable 
          command: sudo chmod -R +x ./.circleci/*.sh
      - run:
          name: Environment variables
          #command: CC=/usr/bin/gcc-7 && CXX=/usr/bin/g++-7
      - run:
          name: Build
          command: ./.circleci/script_desktop.sh
      - run:
          name: Codecov upload
          command: bash <(curl -s https://codecov.io/bash)
  build-linux-clang-5:
    machine: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get remove cmake cmake-data
            sudo apt-add-repository -y "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main"
            sudo apt-add-repository -y ppa:george-edison55/cmake-3.x
            sudo apt-get update
            sudo apt-get -y install clang-5.0 lcov cmake
            sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-5.0. 60 --slave /usr/bin/clang++ cnalg++ /usr/bin/clang++-5.0
            sudo update-alternatives --config clang
      - run:
          name: Make scripts executable 
          command: sudo chmod -R +x ./.circleci/*.sh
      - run:
          name: Environment variables
          command: CC=/usr/bin/clang-5.0 && CXX=/usr/bin/clang++-5.0
      - run:
          name: Build
          command: ./.circleci/script_desktop.sh
  build-macos-9-2:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: COMPILER=clang++
      - run:
          name: Install dependencies
          command: brew install cmake lcov
      - run:
          name: Make scripts executable 
          command: sudo chmod -R +x ./.circleci/*.sh
      - run:
          name: Build
          command: ./.circleci/script_desktop.sh
  build-macos-9-3:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: brew install cmake lcov
      - run:
          name: Make scripts executable 
          command: sudo chmod -R +x ./.circleci/*.sh
      - run:
          name: Build
          command: ./.circleci/script_desktop.sh

workflows:
  version: 2
  build:
    jobs:
      - build-linux-default
      - build-linux-gcc7
      - build-linux-clang-5
      - build-macos-9-2
      - build-macos-9-3
      
